// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVj5LbSJGGCuajAmSqA0TULH_Vtf0qPg4',
    appId: '1:279321158778:web:6761e9d7bab191acea47c3',
    messagingSenderId: '279321158778',
    projectId: 'slicr-9a893',
    authDomain: 'slicr-9a893.firebaseapp.com',
    databaseURL: 'https://slicr-9a893-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slicr-9a893.appspot.com',
    measurementId: 'G-L9G23CNZC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPb-YoeMow-0xUy_GXAh52ElMCrZ_mu7U',
    appId: '1:279321158778:android:335aa748b1a0f3c1ea47c3',
    messagingSenderId: '279321158778',
    projectId: 'slicr-9a893',
    databaseURL: 'https://slicr-9a893-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slicr-9a893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamXLh0mb3YMYCWrwjCazjFc4zV6y3NpA',
    appId: '1:279321158778:ios:914ea8d883b72c1bea47c3',
    messagingSenderId: '279321158778',
    projectId: 'slicr-9a893',
    databaseURL: 'https://slicr-9a893-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slicr-9a893.appspot.com',
    iosBundleId: 'com.example.slicr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamXLh0mb3YMYCWrwjCazjFc4zV6y3NpA',
    appId: '1:279321158778:ios:35cff85d80663213ea47c3',
    messagingSenderId: '279321158778',
    projectId: 'slicr-9a893',
    databaseURL: 'https://slicr-9a893-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'slicr-9a893.appspot.com',
    iosBundleId: 'com.example.slicr.RunnerTests',
  );
}
